#!/bin/sh
#
# (C) 2006 Thralling Penguin LLC. All rights reserved.
#
DRVS=zaptel
REM_DRV=/usr/sbin/rem_drv
if [ "${BASEDIR}" = "/" ]; then
	REM_DRV_FLAGS=
else
	REM_DRV_FLAGS="-b ${BASEDIR}"
fi

for DRV in ${DRVS}
do
	${REM_DRV} ${REM_DRV_FLAGS} ${DRV}
done
exit 0

